controller_list:
  - name: fake_robot_arm_controller
    joints:
      - base_link__link1
      - link1__link2
      - link2__link3
      - link3__link4
      - link4__link5
      - link5__link6
      - link6__link7
  - name: fake_ef_controller
    joints:
      - link6__link7